import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Group } from '../src/engine/index.js';
import { parseGLB } from '../src/engine/loaders/GLTF.js';
import { SkinnedModel } from '../src/engine/render/Skinning.js';
import { RemoteAvatar, avatarTriangles } from '../src/player/RemoteAvatar.js';
import { DEFAULT_APPEARANCE } from '../src/player/AvatarAppearance.js';

const male = parseGLB(readFileSync(new URL('../public/models/characters/stock-player.glb', import.meta.url)));
const female = parseGLB(readFileSync(new URL('../public/models/characters/stock-female.glb', import.meta.url)));
assert.equal(avatarTriangles(male), 7364); assert.equal(avatarTriangles(female), 8732);
for (const source of [male, female]) for (const clip of ['idle', 'walk', 'run', 'helm']) assert.ok(source.animations.some(a => a.name === clip));
const created = [];
function model() {
	const result = { group: new Group(), materials: [{ uniforms: { shirt: { value: null } } }], disposed: 0, clipNames: () => ['idle', 'walk', 'run', 'helm'], play(clip) { this.current = clip; }, update(dt) { this.dt = dt; }, dispose() { this.disposed++; } };
	created.push(result); return result;
}
let resolveMale;
const avatar = new RemoteAvatar({ loadSource: asset => asset === 'stock-player' ? new Promise(resolve => { resolveMale = resolve; }) : Promise.resolve(female), createModel: async () => model() });
await avatar.setAppearance({ ...DEFAULT_APPEARANCE, style: 'female' });
const current = avatar.model;
resolveMale(male); await Promise.resolve(); await Promise.resolve();
assert.equal(avatar.model, current, 'Obsolete asset load cannot replace latest style');
await avatar.setAppearance({ ...DEFAULT_APPEARANCE, style: 'female', shirt: '#123456' });
assert.equal(created.length, 1, 'Color changes reuse model');
assert.ok(current.materials[0].uniforms.shirt.value);
avatar.update(.1, { position: [2, 3, 4], yaw: .5, moving: true, mode: 'walk', appearance: avatar.appearance });
assert.deepEqual(avatar.group.position.toArray(), [2, 3, 4]); assert.equal(current.current, 'walk');
avatar.update(.1, { position: [3, 3, 4], yaw: .5, moving: true, mode: 'walk', appearance: avatar.appearance });
assert.equal(current.current, 'run');
const scene = new Group(); scene.add(avatar.group); avatar.dispose(); avatar.dispose();
assert.equal(current.disposed, 1); assert.equal(scene.children.length, 0);
let finishModel;
const pending = new RemoteAvatar({ loadSource: async () => male, createModel: () => new Promise(resolve => { finishModel = resolve; }) });
await Promise.resolve(); pending.dispose(); const late = model(); finishModel(late); await pending.ready;
assert.equal(late.disposed, 1, 'Model completed after departure releases resources');
const capped = new RemoteAvatar({ maxComplexity: 100, loadSource: async () => male, createModel: async () => { throw new Error('Over-budget model must not be created'); } });
await capped.ready; assert.equal(capped.model, null); assert.equal(capped.fallback.visible, true); capped.dispose();
const tiny = new RemoteAvatar({ maxComplexity: 1, loadSource: async () => male }); await tiny.ready;
assert.equal(tiny.fallback.visible, false); tiny.dispose();
const releases = [];
const resources = { jointBuffer: { destroy: () => releases.push('joints') }, meshes: [{ geometry: { dispose: () => releases.push('geometry') } }], ownedTextures: new Map([['texture', { destroy: () => releases.push('texture') }]]), materials: [{ dispose: () => releases.push('material') }] };
SkinnedModel.prototype.dispose.call(resources); SkinnedModel.prototype.dispose.call(resources);
assert.deepEqual(releases, ['joints', 'geometry', 'texture', 'material'], 'Skinned models release all per-instance GPU resources once');
console.log('Remote avatar: assets, style races, color reuse, movement, disposal and complexity limits passed');

const lodAssets = [];
const lod = new RemoteAvatar({loadSource: async asset => { lodAssets.push(asset); return male; }, createModel: async () => model()});
await lod.ready;
const fullModel = lod.model;
lod.setViewDistance(20); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player-medium');
assert.equal(fullModel.disposed, 1);
lod.setViewDistance(16); await lod.ready;
assert.equal(lodAssets.length, 2, 'Distance hysteresis avoids repeated switching');
lod.setViewDistance(50); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player-low');
lod.setViewDistance(40); await lod.ready;
assert.equal(lodAssets.length, 3);
lod.setViewDistance(10); await lod.ready;
assert.equal(lodAssets.at(-1), 'stock-player');
lod.dispose();
console.log('Avatar distance LOD switching, recovery and hysteresis passed');
